# Find entities with multiple line/polygon annotations
Select * From <http://linkedgeodata.org> {
    { 
        Select ?s, Count(*) As ?c From <http://test.org> {
            ?s ?p1 ?o1 .
            ?s ?p2 ?o2 .
            Filter(
            	?p1 In (<http://www.georss.org/georss/line>, <http://www.georss.org/georss/polygon>) &&
            	?p2 In (<http://www.georss.org/georss/line>, <http://www.georss.org/georss/polygon>) &&
            	((?p1 != ?p2) || (?o1 != ?o2))
            ) .
        }
    } . Filter(?c > 0) .
}

# Find number of all annotated ways
Select Count(*) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?p In (<http://www.georss.org/georss/line>, <http://www.georss.org/georss/polygon>)) .
}

# Find number of nodes
Select Count(Distinct ?s) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?s Like "http://linkedgeodata.org/triplify/node%") .
}

# Find number of ways
Select Count(Distinct ?s) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?s Like "http://linkedgeodata.org/triplify/way%") .
}



# Find ways without georss polygon or way
Select ?s From <http://linkedgeodata.org> {
	?s ?p ?o .
	Filter(?s Like "http://linkedgeodata.org/triplify/way%") .

	Optional {
		?s ?x ?y
		Filter(?x In (<http://www.georss.org/georss/line>, <http://www.georss.org/georss/polygon>)) .
	}
	Filter(!Bound(?s)) .
}


# Find dangling nodes
# These are nodes without relevant tags that are not referenced by ways
# Note: For now we are looking for ways with only a single tag
Select ?s From <http://test.org> {
    {
    { 
		Select ?s, Count(*) As ?c From <http://test.org> {
			?s ?p ?o .
		}
    }
	Filter(?c = 1) .
	}
    Optional {
    	?wn ?i ?s .
    }
    Filter(!Bound(?wn)) .
}

# Retrieve a node and all its references
Select ?s ?p ?o From<http://linkedgeodata.org> {
  {
    ?s ?p ?o .
  }
  Union {
    ?o ?p ?s .
  }
  Filter(?s = <http://linkedgeodata.org/triplify/node922837330>) .
}