# Count nodes
Select Count(Distinct ?s) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?s Like "http://linkedgeodata.org/triplify/node%") .
}

# Count ways
Select Count(Distinct ?s) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?s Like "http://linkedgeodata.org/triplify/way%") .
}

# Count wayNodes [tested]
Select Count(Distinct ?s) From <http://linkedgeodata.org> {
		?s ?p ?o .
		Filter(?s Like "http://linkedgeodata.org/triplify/way%/nodes") .
}
